# Database Connection Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/buildcon_erp?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configurations
# Secret key should be at least 256 bits (32 bytes) long base64 encoded or a long string
buildcon.app.jwtSecret=======================BuildconERPSecretKeyForSecurityAuthenticationJWT======================
buildcon.app.jwtExpirationMs=86400000

# Server Configuration
server.port=8081
