# Database Connection Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/buildcon_erp?useSSL=true&sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2,TLSv1.3}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:4VH3kSZ5tX9DuhK.root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bGLrEERcK1tgb6lh}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA & Hibernate Configurations
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configurations
# Secret key should be at least 256 bits (32 bytes) long base64 encoded or a long string
buildcon.app.jwtSecret=${BUILDCON_APP_JWTSECRET:=======================BuildconERPSecretKeyForSecurityAuthenticationJWT======================}
buildcon.app.jwtExpirationMs=${BUILDCON_APP_JWTEXPIRATIONMS:86400000}

# Server Configuration
server.port=${PORT:8081}
