package com.buildcon.erp.model;

public enum ERole {
    ROLE_ADMIN,
    ROLE_USER,
    ROLE_CHAIRMAN,
    ROLE_MD,
    ROLE_PROJECT_DIRECTOR,
    ROLE_BUSINESS_DIRECTOR,
    ROLE_FINANCE_DIRECTOR,
    ROLE_CONSTRUCTION_MANAGER,
    ROLE_PROJECT_MANAGER,
    ROLE_QUANTITY_SURVEYOR,
    ROLE_PROCUREMENT_MANAGER,
    ROLE_FINANCE_ACCOUNTS,
    ROLE_SITE_MANAGEMENT,
    ROLE_WORKFORCE_MANAGER,
    ROLE_SUBCONTRACTOR,
    ROLE_SENIOR_SITE_ENGINEER,
    ROLE_DIGITAL_MARKETING_TL,
    ROLE_DIGITAL_MARKETING_EXECUTIVE,
    ROLE_SALES_EXECUTIVE,
    ROLE_MARKETING_MANAGER,
    ROLE_HR_MANAGER
}
